const defaultSurveyJSON = {
    "title": "Pyxida Survey",
    "showProgressBar": "top",
    "pages": [
        {
        "name": "page1",
        "elements": [
        {
            "type": "text",
            "name": "question1",
            "title": "How old are you?",
            "isRequired": true,
            "validators": [
                {
                "type": "numeric",
                "text": "User cannot be less than 11 years old or more than 26 years old. ",
                "minValue": 11,
                "maxValue": 26
                }
            ]
        },
        {
            "type": "nouislider",
            "name": "question2",
            "title": "How much do you care about the reputation of your community college?",
            "isRequired": true
        },
        {
            "type": "nouislider",
            "name": "question4",
            "title": "What is your current financial situation?",
            "isRequired": true
        },
        {
            "type": "nouislider",
            "name": "question3",
            "title": "What would be your estimated amount of financial aid needed?",
            "isRequired": true,
        },
        {
            "type": "radiogroup",
            "name": "question5",
            "title": "Are you a domestic or international student?",
            "isRequired": true,
            "choices": [
            {
            "value": "Item 1",
            "text": "Domestic"
            },
            {
            "value": "Item 2",
            "text": "International"
            }
            ]
        },
        {
            "type": "dropdown",
            "name": "question5.1",
            "visible": false,
            "visibleIf": "{question5} = 'Item 1'",
            "title": "Which state do you live in?",
            "isRequired": true,
            "choices": [
                'Alabama',
                'Alaska',
                'Arizona',
                'Arkansas',
                'California',
                'Colorado',
                'Connecticut',
                'Delaware',
                'Florida',
                'Georgia',
                'Hawaii',
                'Idaho',
                'Illinois',
                'Indiana',
                'Iowa',
                'Kansas',
                'Kentucky',
                'Louisiana',
                'Maine',
                'Maryland',
                'Massachusetts',
                'Michigan',
                'Minnesota',
                'Mississippi',
                'Missouri',
                'Montana',
                'Nebraska',
                'Nevada',
                'New Hampshire',
                'New Jersey',
                'New Mexico',
                'New York',
                'North Carolina',
                'North Dakota',
                'Ohio',
                'Oklahoma',
                'Oregon',
                'Pennsylvania',
                'Rhode Island',
                'South Carolina',
                'South Dakota',
                'Tennessee',
                'Texas',
                'Utah',
                'Vermont',
                'Virginia',
                'Washington',
                'West Virginia',
                'Wisconsin',
                'Wyoming'
            ]
        },
        {
            "type": "boolean",
            "name": "question5.2",
            "visible": false,
            "visibleIf": "{question5} = 'Item 1'",
            "title": "Are you a US-Citizen/Green Card holder?",
            "isRequired": true
        },
        {
            "type": "checkbox",
            "name": "question6",
            "title": "What is your ethnicity(s)?",
            "isRequired": true,
            "choices": [
            {
            "value": "Item 3",
            "text": "White"
            },
            {
            "value": "Item 5",
            "text": "Black or African American"
            },
            {
            "value": "Item 4",
            "text": "Asian"
            },
            {
            "value": "Item 6",
            "text": "Native American or Indigenous"
            },
            {
            "value": "Item 7",
            "text": "Pacific Islander"
            },
            {
            "value": "Item 8",
            "text": "Latino or Hispanic"
            },
            {
            "value": "Item 12",
            "text": "Other"
            },
            {
            "value": "Item 13",
            "text": "Rather not specify"
            }
            ]
        },
        {
            "type": "radiogroup",
            "name": "question7",
            "title": "What is your gender?",
            "isRequired": true,
            "choices": [
            {
            "value": "Item 1",
            "text": "Male"
            },
            {
            "value": "Item 2",
            "text": "Female"
            },
            {
            "value": "Item 4",
            "text": "Non-Binary"
            },
            {
            "value": "Item 3",
            "text": "Other"
            }
            ]
        },
        {
            "type": "radiogroup",
            "name": "question8",
            "title": "What is your religion?",
            "isRequired": true,
            "choices": [
            {
            "value": "Item 6",
            "text": "Christianity"
            },
            {
            "value": "Item 12",
            "text": "Islam"
            },
            {
            "value": "Item 13",
            "text": "Judaism"
            },
            {
            "value": "Item 14",
            "text": "Buddhism"
            },
            {
            "value": "Item 17",
            "text": "Pagan/Folk/Local religions"
            },
            {
            "value": "Item 18",
            "text": "Other"
            },
            {
            "value": "Item 19",
            "text": "Non-religious"
            }
            ]
        },
        {
            "type": "radiogroup",
            "name": "question9",
            "title": "How would you describe your political beliefs?",
            "isRequired": true,
            "choices": [
            {
            "value": "Item 1",
            "text": "Centre"
            },
            {
            "value": "Item 2",
            "text": "Left-Leaning"
            },
            {
            "value": "Item 3",
            "text": "Liberal"
            },
            {
            "value": "Item 4",
            "text": "Conservative"
            },
            {
            "value": "Item 5",
            "text": "Right-Leaning"
            },
            {
            "value": "Item 6",
            "text": "I do not involve in politics"
            },
            {
            "value": "Item 7",
            "text": "I prefer not to say"
            }
            ]
        },
        {
            "type": "radiogroup",
            "name": "question10",
            "title": "What is your sexual orientation?",
            "isRequired": true,
            "choices": [
            {
            "value": "Item 1",
            "text": "Heterosexual"
            },
            {
            "value": "Item 2",
            "text": "Homosexual"
            },
            {
            "value": "Item 3",
            "text": "Bisexual"
            },
            {
            "value": "Item 4",
            "text": "Others"
            },
            {
            "value": "Item 5",
            "text": "Rather not specify"
            }
            ]
        }
        ],
        "title": "Student Info",
        "description": "Basic Information About Student"
        },
        {
        "name": "page2",
        "elements": [
        {
            "type": "nouislider",
            "name": "question11",
            "title": "Do you enjoy school?",
            "isRequired": true
        },
        {
            "type": "nouislider",
            "name": "question12",
            "title": "Do you frequently complete your academic work on time?",
            "isRequired": true
        },
        {
            "type": "tagbox",
            "name": "question13",
            "title": "Which fields are you interested in and would like to pursue?",
            "isRequired": true,
            "choices": [
            //list of academic fields
            'Accounting',
            'Agriculture',
            'Anthropology',
            'Architecture',
            'Art',
            'Biology',
            'Business',
            'Chemistry',
            'Communications',
            'Computer Science',
            'Criminal Justice',
            'Dance',
            'Economics',
            'Education',
            'Engineering',
            'English',
            'Environmental Science',
            'Film',
            'Finance',
            'Geography',
            'Geology',
            'Graphic Design',
            'Health',
            'History',
            'Hospitality',
            'Human Resources',
            'Information Technology',
            'International Relations',
            'Journalism',
            'Law',
            'Other'
            ]
        },
        {
            "type": "tagbox",
            "name": "question14",
            "title": "What career field do you want to pursue after college?",
            "isRequired": true,
            "choices": [
            //List of Career Fields
            'Accounting',
            'Agriculture',
            'Anthropology',
            'Architecture',
            'Art',
            'Biology',
            'Business',
            'Chemistry',
            'Communications',
            'Computer Science',
            'Criminal Justice',
            'Dance',
            'Economics',
            'Education',
            'Engineering',
            'English',
            'Environmental Science',
            'Film',
            'Finance',
            'Geography',
            'Geology',
            'Graphic Design',
            'Health',
            'History',
            'Hospitality',
            'Human Resources',
            'Information Technology',
            'International Relations',
            'Journalism',
            'Law',
            'Other'
            ]
        },
        {
            "type": "tagbox",
            "name": "question16",
            "visible": false,
            "title": "Where would you like to study? (States)",
            "isRequired": true,
            "showSelectAllItem": true,
            "choices": [
            'Alabama',
            'Alaska',
            'Arizona',
            'Arkansas',
            'California',
            'Colorado',
            'Connecticut',
            'Delaware',
            'Florida',
            'Georgia',
            'Hawaii',
            'Idaho',
            'Illinois',
            'Indiana',
            'Iowa',
            'Kansas',
            'Kentucky',
            'Louisiana',
            'Maine',
            'Maryland',
            'Massachusetts',
            'Michigan',
            'Minnesota',
            'Mississippi',
            'Missouri',
            'Montana',
            'Nebraska',
            'Nevada',
            'New Hampshire',
            'New Jersey',
            'New Mexico',
            'New York',
            'North Carolina',
            'North Dakota',
            'Ohio',
            'Oklahoma',
            'Oregon',
            'Pennsylvania',
            'Rhode Island',
            'South Carolina',
            'South Dakota',
            'Tennessee',
            'Texas',
            'Utah',
            'Vermont',
            'Virginia',
            'Washington',
            'West Virginia',
            'Wisconsin',
            'Wyoming'
            ]
        },
        {
            "type": "checkbox",
            "name": "question17",
            "visible": false,
            "title": "Where would you like to study? (City)",
            "isRequired": true,
            "showSelectAllItem": true
        },
        {
            "type": "checkbox",
            "name": "question18",
            "visible": false,
            "title": "Where would you like to study? (Town)",
            "isRequired": true,
            "showSelectAllItem": true
        }
        ]
        },
        {
        "name": "page3",
        "elements": [
        {
            "type": "nouislider",
            "name": "question19",
            "title": "How social would you prefer your environment to be? (Low for casual and high for academic)",
            "isRequired": true
        },
        {
            "type": "nouislider",
            "name": "question20",
            "title": "How competitive would you prefer your environment to be?",
            "isRequired": true
        },
        {
            "type": "nouislider",
            "name": "question21",
            "title": "Do you prefer lectures or discussions? (Low for more lectures, high for more discussion)",
            "isRequired": true
        },
        {
            "type": "checkbox",
            "name": "question22",
            "title": "What is your most important purpose for being in college?",
            "isRequired": true,
            "choices": [
            {
            "value": "Item 1",
            "text": "Career Preparation"
            },
            {
            "value": "Item 2",
            "text": "Build Status"
            },
            {
            "value": "Item 3",
            "text": "Gain Knowledge in General"
            }
            ]
        },
        {
            "type": "boolean",
            "name": "question23",
            "title": "Are you planning to enter a specialized career in the future, and are you planning to use college to train for it?",
            "isRequired": true
        },
        {
            "type": "boolean",
            "name": "question24",
            "title": "Are study abroad opportunities important for you?",
            "isRequired": true
        },
        {
            "type": "nouislider",
            "name": "question25",
            "title": "How large would you prefer your student body environment to be?",
            "isRequired": true
        },
        {
            "type": "rating",
            "name": "question26",
            "title": "How social would you prefer your environment to be?",
            "isRequired": true
        },
        {
            "type": "boolean",
            "name": "question27",
            "title": "Are you planning to make leisure activities (parties, etc.) a big part of your college life?",
            "isRequired": true
        },
        {
            "type": "radiogroup",
            "name": "question28",
            "title": "Would you prefer dormitories or external housing?",
            "isRequired": true,
            "choices": [
            {
            "value": "Item 1",
            "text": "Dormitories"
            },
            {
            "value": "Item 2",
            "text": "External Housing"
            },
            {
            "value": "Item 3",
            "text": "Don't Care"
            }
            ]
        },
        {
            "type": "nouislider",
            "name": "question29",
            "title": "How much do you value campus food?",
            "isRequired": true
        },
        {
            "type": "ranking",
            "name": "question30",
            "title": "Rank the following factors from most to least important to you:    (drag and drop)",
            "isRequired": true,
            "choices": [
            {
            "value": "Item 1",
            "text": "How well the school fits your academic interests"
            },
            {
            "value": "Item 2",
            "text": "Variety of courses and degrees that the college offers"
            },
            {
            "value": "Item 3",
            "text": "Campus culture and society"
            },
            {
            "value": "Item 4",
            "text": "Emphasis on career preparation"
            },
            {
            "value": "Item 5",
            "text": "Study abroad opportunities"
            },
            {
            "value": "Item 6",
            "text": "Socializing on campus"
            },
            {
            "value": "Item 7",
            "text": "Racial and gender diversity"
            },
            {
            "value": "Item 8",
            "text": "Leisure activities"
            },
            {
            "value": "Item 9",
            "text": "Co-curricular activities"
            },
            {
            "value": "Item 10",
            "text": "Frats and sororities"
            },
            {
            "value": "Item 11",
            "text": "Location"
            },
            {
            "value": "Item 12",
            "text": "Saving costs and finding financial benefits"
            }
            ]
        },
        {
            "type": "nouislider",
            "name": "question31",
            "title": "What would be the optimal student to teacher ratio for you?",
            "isRequired": true
        },
        {
            "type": "boolean",
            "name": "question32",
            "title": "Would you want to enter a frat or sorority (social organizations)?",
            "isRequired": true
        }
        ]
        },
        {
        "name": "page4",
        "elements": [
        {
            "type": "checkbox",
            "name": "question33",
            "title": "Which of the below do you prefer?",
            "isRequired": true,
            "choices": [
            {
            "value": "Item 1",
            "text": "Bachelor's degree"
            },
            {
            "value": "Item 2",
            "text": "Associates degree"
            }
            ]
        },
        {
            "type": "checkbox",
            "name": "question34",
            "title": "What co-curricular activities would you be interested in?",
            "isRequired": true,
            "choices": [
            {
            "value": "Item 1",
            "text": "Sports"
            },
            {
            "value": "Item 2",
            "text": "Music"
            },
            {
            "value": "Item 3",
            "text": "Art"
            },
            {
            "value": "Item 4",
            "text": "Others"
            }
            ]
        },
        {
            "type": "tagbox",
            "name": "question35",
            "title": "What sports do you play?",
            "isRequired": true,
            "choices": [
                "Breakdancing",
                "Competitive dancing",
                "Cheerleading",
                "Dancesport",
                "Dragon dance and Lion dance",
                "Figure skating",
                "Freerunning",
                "Gymnastics",
                "High kick",
                "Parkour",
                "Pole sports",
                "Stunt",
                "Trampolining",
                "Winter guard",
                "Aerobatics",
                "Air racing",
                "Cluster ballooning",
                "Hopper ballooning",
                "Wingsuit flying",
                "Gliding",
                "Hang gliding",
                "Powered hang glider",
                "Human powered aircraft",
                "Model aircraft",
                "Parachuting",
                "Banzai skydiving",
                "BASE jumping",
                "Skysurfing",
                "Wingsuit flying",
                "Paragliding",
                "Paramotoring",
                "Ultralight aviation",
                "3D archery",
                "Field archery",
                "Flight archery",
                "Gungdo",
                "Indoor archery",
                "Kyūdō",
                "Mounted archery",
                "Popinjay",
                "Run archery",
                "Target archery",
                "Skateboarding",
                "Casterboarding",
                "Freeboard (skateboard)",
                "Longboarding",
                "Streetboarding",
                "Scootering",
                "Skysurfing",
                "Streetluge",
                "Snowboarding",
                "Mountainboarding",
                "Sandboarding",
                "Snowkiting",
                "Surfing",
                "Bodyboarding",
                "Dog surfing",
                "Riverboarding",
                "Skimboarding",
                "Wakesurfing",
                "Windsurfing",
                "Wakeboarding",
                "Kneeboarding",
                "Paddleboarding",
                "Dodgeball",
                "Frisbee",
                "Gaga",
                "Keep away",
                "Kin-Ball",
                "Newcomb ball",
                "Quidditch",
                "Yukigassen",
                "Abseiling",
                "Aid climbing",
                "Ice climbing",
                "Mixed climbing",
                "Mountaineering",
                "Rock climbing",
                "Bouldering",
                "Deep-water soloing",
                "Sport climbing",
                "Traditional climbing",
                "Speed climbing",
                "Sawanobori",
                "Canyoning (Canyoneering)",
                "Coasteering",
                "Hiking",
                "Rope climbing",
                "Pole climbing",
                "Artistic cycling",
                "BMX",
                "Cyclo-cross",
                "Cycle polo",
                "Cycle speedway",
                "Downhill mountain biking",
                "Dirt jumping",
                "Freestyle BMX",
                "Hardcourt Bike Polo",
                "Mountain biking",
                "Road bicycle racing",
                "Track cycling",
                "Underwater cycling",
                "Cycle ball",
                "Skibobbing",
                "Mountain unicycling",
                "Street unicycling",
                "Unicycling",
                "Unicycle basketball",
                "Unicycle hockey",
                "Unicycle trials",
                "Aiki-jūjutsu",
                "Aikido",
                "Jujutsu",
                "Judo",
                "Brazilian jiu-jitsu",
                "Sambo (martial art)",
                "Sumo",
                "Wrestling",
                "Amateur wrestling",
                "Greco-Roman wrestling",
                "Freestyle wrestling",
                "Folk wrestling",
                "Boli Khela",
                "Catch wrestling",
                "Collar-and-elbow",
                "Collegiate wrestling",
                "Cornish wrestling",
                "Devon wrestling",
                "Dumog",
                "Glima",
                "Gouren",
                "Kurash",
                "Lancashire wrestling",
                "Malla-yuddha",
                "Mongolian wrestling",
                "Pehlwani",
                "Schwingen",
                "Shuai jiao",
                "Ssireum",
                "Varzesh-e Pahlavani",
                "Yağlı Güreş",
                "Greek wrestling",
                "Mud wrestling",
                "Oil wrestling",
                "Professional wrestling",
                "A kick in kickboxing.",
                "A kick in kickboxing.",
                "Bajiquan",
                "Bokator",
                "Boxing",
                "Capoeira",
                "Chess boxing",
                "Choi Kwang-Do",
                "Fujian White Crane",
                "Karate",
                "Kenpō",
                "Kickboxing",
                "Lethwei",
                "Muay Thai",
                "Pradal serey",
                "Savate",
                "Shaolin Kung Fu",
                "Shin-kicking",
                "Sikaran",
                "Silat",
                "Subak",
                "Taekkyeon",
                "Taekwondo",
                "Taidō",
                "Tang Soo Do",
                "Vovinam",
                "Wing Chun",
                "Bare knuckle boxing",
                "Competitive Slapping",
                "American Kenpo",
                "Baguazhang",
                "Bando",
                "Bartitsu",
                "Bujinkan",
                "Hapkido",
                "Chun Kuk Do",
                "Hwa Rang Do",
                "Jeet Kune Do",
                "Kajukenbo",
                "Kalaripayattu",
                "Krav Maga",
                "Kuk Sool Won",
                "Marine Corps Martial Arts Program",
                "Mixed martial arts",
                "Northern Praying Mantis",
                "Ninjutsu",
                "Okichitaw",
                "Pankration",
                "Pencak Silat",
                "Sanda",
                "Shidōkan Karate",
                "Shōrin-ryū Shidōkan",
                "Shooto",
                "Shoot boxing",
                "Shootfighting",
                "Shorinji Kempo",
                "Systema",
                "T'ai chi ch'uan",
                "Unifight",
                "Vajra-mushti",
                "Vale tudo",
                "Xing Yi Quan",
                "Zen Bu Kan Kempo",
                "Two kendōka.",
                "Battōjutsu",
                "Bojutsu",
                "Boffer fighting",
                "Buhurt",
                "Canne de combat",
                "Cardboard Tube Fighting",
                "Eskrima",
                "Egyptian stick fencing",
                "Fencing",
                "Gatka",
                "Historical European martial arts",
                "Hojōjutsu",
                "Iaidō",
                "Iaijutsu",
                "Jōdō",
                "Jogo do pau",
                "Jūkendō",
                "Jittejutsu",
                "Kendo",
                "Kenjutsu",
                "Krabi–krabong",
                "Kumdo",
                "Kung fu",
                "Kyūdō",
                "Kyūjutsu",
                "Medieval MMA",
                "Modern Arnis",
                "Naginatajutsu",
                "Nguni stick-fighting",
                "Okinawan kobudō",
                "Shurikenjutsu",
                "Silambam",
                "Sōjutsu",
                "Sword fighting",
                "Wing Chun",
                "Wushu",
                "lathi khela",
                "Disc dog",
                "Disc golf",
                "Disc golf (urban)",
                "Dodge disc",
                "Double disc court",
                "Freestyle",
                "Fricket",
                "Frisbee",
                "Goaltimate",
                "KanJam",
                "Guts",
                "Flutterguts",
                "Hot box",
                "Ultimate",
                "Acrobatic gymnastics",
                "Aerial hoop",
                "Aerial silks",
                "Aerobic gymnastics",
                "Artistic gymnastics",
                "Balance beam",
                "Floor",
                "High bar",
                "Parallel bars",
                "Pommel horse",
                "Still rings",
                "Uneven bars",
                "Vault",
                "Juggling",
                "Baton twirling",
                "Parkour",
                "Rhythmic gymnastics",
                "Ball Rhythmic gymnastics",
                "Club Rhythmic gymnastics",
                "Hoop Rhythmic gymnastics",
                "Ribbon Rhythmic gymnastics",
                "Rope Rhythmic gymnastics",
                "Rope jumping",
                "Pole dance",
                "Rope climbing",
                "Slacklining",
                "Trampolining",
                "Trapeze",
                "Flying trapeze",
                "Static trapeze",
                "Tumbling",
                "Wheel gymnastics",
                "Calisthenics",
                "Competitive Yoga",
                "Ice Tennis",
                "Bandy",
                "Rink bandy",
                "Barrel jumping",
                "Broomball",
                "Crokicurl",
                "Curling",
                "Figure skating",
                "Single skating",
                "Pair skating",
                "Ice dancing",
                "Synchronized skating",
                "Four skating",
                "Ice theatre",
                "Ice cross downhill",
                "Ice football",
                "Ice baseball",
                "Ice hockey",
                "Sledge hockey",
                "Spongee",
                "Ice yachting",
                "Moscow broomball",
                "Ringette",
                "Rinkball",
                "Speed skating",
                "Short track speed skating",
                "Long track speed skating",
                "Ice stock sport",
                "Hang gliding",
                "Kite buggy",
                "Kite fighting",
                "Kite landboarding",
                "Kitesurfing",
                "Parasailing",
                "Snow kiting",
                "Sport kite (Stunt kite)",
                "Adventure racing",
                "Aquathlon",
                "Biathlon",
                "Duathlon",
                "Decathlon",
                "Heptathlon",
                "Icosathlon",
                "Modern pentathlon",
                "Pentathlon",
                "Tetrathlon",
                "Triathlon",
                "Amateur radio direction finding (Radio Orienteering)",
                "Geocaching",
                "Geohashing",
                "Letterboxing",
                "Orienteering",
                "Rogaining",
                "Waymarking",
                "Freerunning",
                "Martial Arts Tricking",
                "Ninja Warrior",
                "Obstacle racing (OCR)",
                "Parkour",
                "Trampolining",
                "World Chase Tag",
                "5K run",
                "10K run",
                "Cross-country running",
                "Half marathon",
                "Marathon",
                "Road running",
                "Ekiden",
                "Tower running",
                "Ultramarathon",
                "Snowshoe running",
                "Fell running",
                "Trail running",
                "Mountain running",
                "Skyrunning",
                "Sprint",
                "Hurdles",
                "Dinghy sailing",
                "Ice yachting",
                "Kiteboarding",
                "Land sailing",
                "Land windsurfing",
                "Sailing",
                "Windsurfing",
                "Wing foiling",
                "Yacht racing",
                "Broomball",
                "Freestyle skiing",
                "Aerials",
                "Moguls",
                "Halfpipe",
                "Slopestyle",
                "Ski cross",
                "Ski ballet",
                "Speed skiing",
                "Nordic skiing",
                "Cross-country skiing",
                "Ski jumping",
                "Nordic combined",
                "Telemark skiing",
                "Ski mountaineering",
                "Ski touring",
                "Skijoring",
                "Bobsleigh",
                "Luge",
                "Shovel racing",
                "Skibobbing",
                "Skeleton",
                "Toboggan",
                "Shooting",
                "Clay pigeon shooting",
                "Skeet shooting",
                "Trap shooting",
                "Sporting clays",
                "Slingshotting",
                "Bullseye shooting",
                "Rifle",
                "ISSF rifle events",
                "Fullbore target rifle",
                "High power rifle",
                "Benchrest shooting",
                "Paralympic rifle events",
                "ISSF pistol events",
                "Paralympic pistol events",
                "Field shooting",
                "Precision rifle competition",
                "Precision Rifle Series",
                "Field target",
                "Metallic silhouette shooting",
                "ICFRA Palma and F-Class",
                "Plinking",
                "Practical shooting",
                "International Practical Shooting Confederation (IPSC)",
                "International Defensive Pistol Association (IDPA)",
                "Multigun",
                "Cowboy action shooting",
                "Olympic dueling",
                "Match crossbow",
                "Modern pentathlon",
                "Biathlon",
                "Summer biathlon",
                "Ski field shooting",
                "Field running",
                "Moose biathlon",
                "Target sprint",
                "Pistol skiing",
                "Orienteering shooting",
                "Military patrol",
                "Underwater target shooting",
                "Water baseball",
                "Air baseball",
                "Ice baseball",
                "Airsoft",
                "Laser tag",
                "Paintball",
                "Card stacking",
                "Cup stacking",
                "Dice stacking",
                "Sport stacking",
                "Free running",
                "Freestyle footbag",
                "Freestyle football",
                "Powerbocking",
                "Parkour",
                "Scootering",
                "Street workout",
                "Strongman",
                "Atya-patya",
                "Bo-taoshi",
                "British Bulldog (American Eagle; Australian Dingo)",
                "Capture the flag",
                "Darebase",
                "Hana Ichi Monme",
                "Hide and seek",
                "Jugger",
                "Kabaddi",
                "Kho kho",
                "Kick the can",
                "Langdi",
                "Marco Polo",
                "Oztag",
                "Red rover",
                "Tag",
                "World Chase Tag",
                "Backpacking (hiking)",
                "Bushwhacking",
                "Hiking",
                "Racewalking",
                "Walking",
                "Canoeing",
                "Outrigger canoeing",
                "Creeking",
                "Flyak",
                "Freeboating",
                "Sea kayaking",
                "Squirt boating",
                "Surf kayaking",
                "Whitewater kayaking",
                "Rafting",
                "White water rafting",
                "Rowing",
                "Gig racing",
                "Coastal and ocean rowing",
                "Surfboat",
                "Single scull",
                "Dragon boat racing",
                "Stand up paddle boarding",
                "Water polo",
                "Canoe polo",
                "Stone skipping",
                "Waboba",
                "Underwater football",
                "Underwater rugby",
                "Underwater hockey",
                "Underwater ice hockey",
                "Backstroke",
                "Breaststroke",
                "Butterfly stroke",
                "Freestyle swimming",
                "Individual medley",
                "Synchronized swimming",
                "Medley relay",
                "Bifins (finswimming)",
                "Surface finswimming",
                "Apnoea finswimming",
                "Aquathlon (underwater wrestling)",
                "Freediving",
                "Immersion finswimming",
                "Scuba diving",
                "Spearfishing",
                "Snorkelling",
                "Sport diving (sport)",
                "Underwater orienteering",
                "Underwater photography (sport)",
                "Underwater target shooting",
                "Cliff diving",
                "Diving",
                "Basque traditional weightlifting",
                "CrossFit",
                "Highland games",
                "Kettlebell lifting",
                "Olympic weightlifting",
                "Powerlifting",
                "Strength athletics (strongman)",
                "Steinstossen",
                "Air racing",
                "Autocross (a.k.a. Slalom)",
                "Autograss",
                "Banger racing",
                "Board track racing",
                "Demolition derby",
                "Desert racing",
                "Dirt track racing",
                "Drag racing",
                "Drifting",
                "Endurance racing",
                "Folkrace",
                "Formula racing",
                "Formula Libre",
                "Formula Student",
                "Hillclimbing",
                "Baseball racing",
                "Ice racing",
                "Kart racing",
                "Land speed records",
                "Legends car racing",
                "Midget car racing",
                "Monster truck",
                "Mud bogging",
                "Off-road racing",
                "Pickup truck racing",
                "Production car racing",
                "Race of Champions",
                "Rally raid",
                "Rallycross",
                "Rallying",
                "Regularity rally",
                "Road racing",
                "Short track motor racing",
                "Snowmobile racing",
                "Sports car racing",
                "Sprint car racing",
                "Street racing",
                "Stock car racing",
                "Time attack",
                "Tractor pulling",
                "Touring car racing",
                "Truck racing",
                "Vintage racing",
                "Wheelstand competition",
                "Drag boat racing",
                "F1 powerboat racing",
                "Hydroplane racing",
                "Jet sprint boat racing",
                "Offshore powerboat racing",
                "Personal water craft",
                "Auto Race",
                "Board track racing",
                "Cross-country rally",
                "Endurance racing",
                "Enduro",
                "Freestyle motocross",
                "Grand Prix motorcycle racing",
                "Grasstrack",
                "Hillclimbing",
                "Ice racing",
                "Ice speedway",
                "Indoor enduro",
                "Motocross",
                "Motorcycle drag racing",
                "Motorcycle speedway",
                "Off-roading",
                "Rally raid",
                "Road racing",
                "Superbike racing",
                "Supercross",
                "Supermoto",
                "Supersport racing",
                "Sidecar racing",
                "Track racing",
                "Trial",
                "TT racing",
                "Free-style moto",
                "ATV Racing",
                "Airsoft",
                "Archery",
                "Paintball",
                "Darts",
                "Chess boxing",
                "Motoball",
                "Whirlyball",
                "Singing",
                "Band",
                "Marching band",
                "Beatboxing",
                "Dog Sports",
                "Buzkashi",
                "Barrel racing",
                "Campdrafting",
                "Cirit",
                "Charreada",
                "Chilean rodeo",
                "Chuckwagon racing",
                "Cross country",
                "Cutting",
                "Dressage",
                "Endurance riding",
                "English pleasure",
                "Equitation",
                "Eventing",
                "Equestrian vaulting",
                "Gymkhana",
                "Harness racing",
                "Hobby horse polo",
                "Trick riding",
                "Horse racing",
                "Horse polo, or polo",
                "Horseball",
                "Jineteada gaucha",
                "Jousting",
                "Mounted games",
                "Mounted archery",
                "Pato",
                "Pleasure driving",
                "Reining",
                "Rodeo",
                "Show hunter (British)",
                "Show jumping",
                "Steeplechase",
                "Sur-papakh",
                "Team penning",
                "Tent pegging",
                "Western pleasure",
                "Angling",
                "Big-game fishing",
                "Casting",
                "Noodling",
                "Spearfishing",
                "Sport fishing",
                "Surf fishing",
                "Rock fishing",
                "Fly fishing",
                "Ice fishing",
                "Bass fishing",
                "Beagling",
                "Big game hunting",
                "Boar hunting",
                "Deer hunting",
                "Fox hunting",
                "Wolf hunting",
                "Bullriding",
                "Miniature Bull Riding",
                "Barrel Racing",
                "Bronc Riding",
                "Saddle Bronc Riding",
                "Bareback Bronc Riding",
                "Pole bending",
                "Roping",
                "Breakaway Roping",
                "Tie-down Roping",
                "Team Roping",
                "Steer Roping",
                "Steer riding",
                "Steer Wrestling",
                "Goat Tying",
                "Baseball",
                "Baseball5",
                "Ice Baseball",
                "Softball",
                "16-inch softball",
                "Fast-pitch softball",
                "Bat and trap",
                "Bete-ombro",
                "Brännboll",
                "Corkball",
                "Cricket",
                "100-ball cricket",
                "Backyard, Beach and Street cricket",
                "Blind cricket",
                "Club cricket",
                "Deaf cricket",
                "First-class cricket",
                "French cricket",
                "Ice cricket",
                "Indoor cricket",
                "Indoor cricket (UK variant)",
                "Kilikiti",
                "Kwik cricket",
                "Last man stands cricket",
                "Limited overs cricket",
                "List A cricket",
                "One-armed versus one-legged cricket",
                "One Day International",
                "Short form cricket",
                "Single wicket/Double wicket",
                "T10 cricket",
                "Tape ball cricket",
                "Tennis ball cricket",
                "Test cricket",
                "Trobriand cricket",
                "Twenty20",
                "Twenty20 International",
                "Windball cricket",
                "Danish longball",
                "Donkey Baseball",
                "Elle",
                "English baseball",
                "Kickball",
                "Lapta",
                "The Massachusetts Game",
                "Matball",
                "Oină",
                "Old cat",
                "Over-the-line",
                "Palant",
                "Pesäpallo",
                "Plaquita",
                "Punchball",
                "Rounders",
                "Schlagball",
                "Scrub baseball",
                "Stickball",
                "Stoolball",
                "Stoop ball",
                "Tee-ball",
                "Town ball",
                "Vigoro",
                "Vitilla",
                "Welsh baseball",
                "Wiffleball",
                "Wireball",
                "Basketball",
                "3x3 basketball",
                "Beach basketball",
                "Deaf basketball",
                "Donkey basketball",
                "Rezball",
                "Streetball",
                "Unicycle basketball",
                "Water basketball",
                "Wheelchair basketball",
                "Cestoball",
                "Flickerball",
                "Korfball",
                "Netball",
                "Fastnet",
                "Indoor netball",
                "Ringball",
                "Slamball",
                "Uball",
                "Haloball",
                "Chinlone",
                "Cuju",
                "Episkyros",
                "Harpastum",
                "Kemari",
                "Ki-o-rahi",
                "Marn Grook",
                "Sepak Takraw",
                "Woggabaliri",
                "Yubi lakpi",
                "Medieval football",
                "Ba game",
                "Caid",
                "Calcio Fiorentino",
                "Camping (game)",
                "Cnapan",
                "Cornish hurling",
                "Haxey Hood",
                "Knattleikr",
                "La soule",
                "Lelo burti",
                "Mob football",
                "Royal Shrovetide Football",
                "Uppies and Downies",
                "Association football",
                "Jorkyball",
                "Paralympic football",
                "CP football",
                "Powerchair Football",
                "Beach soccer",
                "Crab soccer",
                "Fireball",
                "Five-a-side football",
                "Futsal",
                "Ice football",
                "Indoor soccer",
                "Masters Football",
                "Papi fut",
                "Rush goalie",
                "Seven-a-side football",
                "Kings League",
                "Walking football",
                "Street football",
                "Freestyle football",
                "Keepie uppie",
                "Swamp football",
                "Three sided football",
                "Australian football",
                "AFLX",
                "Metro footy",
                "Nine-a-side footy",
                "Rec footy",
                "English school games",
                "Field game",
                "Wall game",
                "Harrow football",
                "Gaelic football",
                "Ladies' Gaelic football",
                "Gridiron football",
                "American football",
                "Eight-man football",
                "Flag football",
                "Indoor football",
                "Arena football",
                "Nine-man football",
                "Six-man football",
                "Sprint football",
                "Street football (American)",
                "Touch football",
                "Unicycle football",
                "XFL rules football (2001, 2020)",
                "Canadian football",
                "Rugby football",
                "Rugby league",
                "Masters Rugby League",
                "Mod league",
                "OzTag",
                "Rugby league nines",
                "Rugby league sevens",
                "Tag rugby",
                "Touch football",
                "Wheelchair rugby league",
                "Rugby union",
                "American flag rugby",
                "Beach rugby",
                "Mini rugby",
                "Rugby sevens",
                "Rugby tens",
                "Rugby X",
                "Snow rugby",
                "Tag rugby",
                "Touch rugby",
                "Wheelchair rugby",
                "Austus",
                "International rules football",
                "Samoa rules",
                "Speedball",
                "Universal football",
                "Volata",
                "Balle à la main",
                "Ballon au poing",
                "Downball",
                "Four Square/FS Handball",
                "Beach handball",
                "Czech handball",
                "Field handball",
                "Goalball",
                "Spikeball",
                "Tchoukball",
                "Torball",
                "Water polo",
                "Wheelchair handball",
                "Rollball",
                "Hornussen",
                "Hockey",
                "Ball hockey",
                "Bando",
                "Bandy",
                "Rink bandy",
                "Broomball",
                "Field hockey",
                "Indoor field hockey",
                "Floorball",
                "Floor hockey",
                "Ice hockey",
                "Pond hockey",
                "Power hockey",
                "Sledge hockey",
                "Underwater ice hockey",
                "Inline sledge hockey",
                "Ringette",
                "Gym ringette",
                "Rinkball",
                "Roller hockey",
                "Roller hockey (quad)",
                "Inline hockey",
                "Inline sledge hockey",
                "Inline skater hockey",
                "Moscow broomball",
                "Rossall Hockey",
                "Spongee",
                "Street hockey",
                "Underwater hockey",
                "Underwater ice hockey",
                "Unicycle hockey",
                "Cammag",
                "Hurling",
                "Camogie",
                "Shinty",
                "Composite rules shinty-hurling",
                "Lacrosse",
                "Box lacrosse",
                "Field lacrosse",
                "Intercrosse",
                "Polocrosse",
                "Women's lacrosse",
                "Polo",
                "Bicycle polo",
                "Canoe polo",
                "Cowboy polo",
                "Elephant polo",
                "Hobby horse polo",
                "Segway polo",
                "Yak polo",
                "Badminton",
                "Ball badminton",
                "Biribol",
                "Bossaball",
                "Fistball",
                "Footbag net",
                "Football tennis",
                "Footvolley",
                "Frescotennis",
                "Jianzi",
                "Jokgu",
                "Miniten",
                "Padel",
                "Peteca",
                "Pickleball",
                "Rocball",
                "Sepak takraw",
                "Sipa",
                "Table squash",
                "Table tennis",
                "Tennis",
                "Beach tennis",
                "Paddle tennis",
                "Platform tennis",
                "Teqball",
                "Throwball",
                "Volleyball",
                "Beach volleyball",
                "Sitting volleyball",
                "Water volleyball",
                "Wallyball",
                "American handball",
                "Australian handball",
                "Basque pelota",
                "Butts Up",
                "Chinese handball",
                "Fives",
                "Gaelic handball",
                "International fronton",
                "Jai alai",
                "Jorkyball",
                "Racquetball",
                "Squash",
                "Squash tennis",
                "Stoop ball",
                "Suicide (game)",
                "Valencian frontó",
                "Wallball",
                "Wallyball",
                "American handball",
                "Australian handball",
                "Basque pelota",
                "Jai alai",
                "Fives",
                "Eton fives",
                "Rugby fives",
                "Frisian handball",
                "Four square",
                "Gaelic handball",
                "Jeu de paume",
                "Longue paume",
                "Palla",
                "Pallone",
                "Patball",
                "Roundnet",
                "Valencian pilota",
                "Llargues",
                "Badminton",
                "Ball badminton",
                "Frontenis",
                "Battledore and shuttlecock",
                "Crossminton",
                "Qianball",
                "Racketlon",
                "Rackets",
                "Racquetball",
                "Real tennis",
                "Road tennis",
                "Soft tennis",
                "Speed-ball",
                "Squash",
                "Hardball squash",
                "Squash tennis",
                "Stické",
                "Tennis",
                "Tennis polo",
                "Touchtennis",
                "Basque pelota",
                "Beach tennis",
                "The Downside Ball Game",
                "Four wall paddleball",
                "Matkot",
                "Miniten",
                "One wall paddleball",
                "Paddle ball",
                "Paddle tennis",
                "Padel",
                "Paleta Frontón",
                "Pan Pong",
                "Pelota mixteca",
                "Pickleball",
                "Pitton",
                "Platform tennis",
                "Sphairee",
                "Stoolball",
                "Table squash",
                "Table tennis (Ping Pong)"
            ]
        },
        {
            "type": "boolean",
            "name": "question36",
            "title": "Would you want to be a part time undergraduate or full-time undergraduate?",
            "isRequired": true
        }
        ]
        }
    ]
}   

const defaultSurveyCSS = {
    header: 'bg-primary text-white p-3',
    body: 'bg-light',
    completedPage: 'p-3'
};

const defaultSurveyDATA = {
    //TODO
};

const defaultSurveyConfig = {
    defaultSurveyCSS,
    defaultSurveyDATA,
    defaultSurveyJSON
}

export default defaultSurveyConfig;
